services:
  db:
    container_name: postgres_playground_db
    image: postgres:16
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

volumes:
  postgres_data: