version: '3.8'

services:
  db:
    container_name: postgres_playground_db
    image: postgres:16
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: postgres_playground_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@versusbrawl.com 
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - db